# Base image
FROM python:3.10-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar as dependências do projeto
COPY requirements.txt ./

# Instalar dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante do código para o container
COPY . .

# Expor a porta que o Django usará
EXPOSE 8000

# Comando para iniciar o servidor de desenvolvimento do Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]